### ISSUE TITLE
Replacing R Graphing code with Python code

### ISSUE THREAD

**Issue by davidayikwei** [Klimaatlas/KAPy#25] opened 2024-02-01 11:01 UTC
Before we get started, please confirm that:
* [X] you have checked the issue list for pre-existing feature requests, including those that have been closed already. If a similar feature request already exists, please comment there instead of opening a duplicate.

**Is your feature request related to a problem? Please describe.**
Using KAPy requires knowledge of R and you need to have R installed. It will be better if everything was in Python.

**Describe the solution you'd like**
Convert existing R code to Python.

**Describe alternatives you've considered**
Non

**Additional context**
Non

**Comment by markpayneatwork** [comment] 2024-02-21 07:05
Duplicate of #20

**Closed by markpayneatwork** 2024-02-21 07:05 UTC
Labels: duplicate, enhancement
